/* Every entry: `s` = the syntax, `d` = one-line "what it does", `ex` = a runnable
   example. Examples run against the sql-prep teaching database and their real
   output is captured at build time. {sec} starts a new section. */
module.exports = [

{sec:'1 · How a query is read', note:'You write a query in one order; the database evaluates it in another. Almost every "why does this not work?" is answered here.'},
{s:'Written order', d:'The order you must TYPE the clauses in. Getting this wrong is a syntax error.',
 ex:null, plain:'SELECT → FROM → JOIN → WHERE → GROUP BY → HAVING → WINDOW → ORDER BY → LIMIT'},
{s:'Execution order', d:'The order the database actually RUNS them in. This is what governs what is visible where.',
 ex:null, plain:'FROM → JOIN/ON → WHERE → GROUP BY → HAVING → SELECT → DISTINCT → ORDER BY → LIMIT'},
{s:'Why an alias fails in WHERE', d:'WHERE runs at step 3, SELECT at step 6 — the alias does not exist yet.',
 ex:null, plain:"SELECT salary*12 AS annual … WHERE annual > 5  ✗   |   … ORDER BY annual  ✓"},
{s:'Grain', d:'What one row of a result represents. Say it out loud before writing anything.',
 ex:"SELECT COUNT(*) AS line_rows, COUNT(DISTINCT o.order_id) AS real_orders FROM orders o JOIN order_items oi ON oi.order_id=o.order_id"},

{sec:'2 · Punctuation, literals & comments', note:'The mechanical rules: where commas go, which quote means what, when brackets are required.'},
{s:', (comma)', d:'Separates items in a LIST — columns, tables, values, GROUP BY keys. Never before FROM or before a closing bracket.',
 ex:"SELECT cust_name, country, segment FROM customers LIMIT 2"},
{s:'Missing comma', d:'Does NOT error — SQL reads the next word as an alias. Silently returns fewer columns.',
 ex:"SELECT emp_name  title FROM employees LIMIT 2"},
{s:"' ' (single quotes)", d:"Wraps a STRING LITERAL — a piece of data.", ex:"SELECT * FROM customers WHERE country = 'India' LIMIT 2"},
{s:'" " (double quotes)', d:'Wraps an IDENTIFIER (table/column name) and makes it case-sensitive. Data in double quotes is an error.',
 ex:'SELECT cust_name AS "Customer Name" FROM customers LIMIT 2'},
{s:"'' (doubled quote)", d:"Escapes an apostrophe inside a string literal.", ex:"SELECT 'O''Brien' AS name"},
{s:'$$ … $$', d:'Dollar quoting — a string containing quotes, with no escaping needed.', ex:"SELECT $$O'Brien$$ AS name"},
{s:'; (semicolon)', d:'Ends a statement. Required when sending several statements at once.', ex:null, plain:'SELECT 1; SELECT 2;'},
{s:'-- comment', d:'Comment to end of line.', ex:"SELECT 1 AS x  -- everything after this is ignored"},
{s:'/* … */', d:'Block comment; may be nested.', ex:"SELECT /* inline note */ 1 AS x"},
{s:'( ) required', d:'Function calls, IN lists, every subquery, INSERT/CREATE column lists, and OVER (…).',
 ex:"SELECT COUNT(*) FROM orders WHERE status IN ('completed','pending')"},
{s:'( ) advised', d:'Around an OR group whenever AND and OR are mixed — AND binds tighter than OR.',
 ex:"SELECT COUNT(*) AS n FROM orders WHERE (status='completed' OR status='pending') AND channel='web'"},
{s:'Case folding', d:'Keywords are case-insensitive. Unquoted identifiers fold to lower case. String COMPARISON is case-sensitive.',
 ex:"SELECT 'Mumbai'='mumbai' AS exact, 'Mumbai' ILIKE 'mumbai' AS insensitive"},

{sec:'3 · SELECT & FROM', note:'Choosing what comes out, and where rows come from.'},
{s:'SELECT expr, …', d:'Lists the output columns. Columns, expressions, literals and function calls all allowed.',
 ex:"SELECT emp_name, salary, salary*12 AS annual, 'INR' AS currency FROM employees LIMIT 3"},
{s:'AS alias', d:'Renames a column or table in the output. Optional keyword, but always write it.',
 ex:"SELECT emp_name AS name, salary AS pay FROM employees LIMIT 2"},
{s:'SELECT *', d:'Every column. Fine while exploring; a liability in production code.', ex:"SELECT * FROM departments LIMIT 2"},
{s:'SELECT DISTINCT', d:'Removes duplicate OUTPUT ROWS (the whole row, not one column).',
 ex:"SELECT DISTINCT country FROM customers ORDER BY country"},
{s:'DISTINCT ON (cols)', d:'PostgreSQL only. Keeps the FIRST row per group given an ORDER BY — "latest record per customer" in one line.',
 ex:"SELECT DISTINCT ON (cust_id) cust_id, order_id, order_date FROM orders ORDER BY cust_id, order_date DESC"},
{s:'FROM table alias', d:'The starting row source. An alias shortens every later reference.',
 ex:"SELECT e.emp_name FROM employees e LIMIT 2"},
{s:'FROM (subquery) AS t', d:'A derived table. The alias is MANDATORY in PostgreSQL.',
 ex:"SELECT t.dept_id, t.n FROM (SELECT dept_id, COUNT(*) AS n FROM employees GROUP BY dept_id) AS t ORDER BY t.n DESC LIMIT 3"},
{s:'FROM (VALUES …) AS t(c)', d:'A literal inline table — useful for lookup/banding tables.',
 ex:"SELECT * FROM (VALUES ('a',1),('b',2)) AS v(letter, num)"},
{s:'generate_series(a,b,step)', d:'A set-returning function used as a table — builds number and date spines.',
 ex:"SELECT g::date AS month FROM generate_series(DATE '2024-01-01', DATE '2024-04-01', INTERVAL '1 month') g"},

{sec:'4 · Comparison operators', note:'Every one of these returns TRUE, FALSE or NULL. WHERE keeps a row only on TRUE.'},
{s:'=', d:'Equal to.', ex:"SELECT COUNT(*) AS n FROM orders WHERE status = 'completed'"},
{s:'<> ', d:'Not equal to. The SQL standard spelling.', ex:"SELECT COUNT(*) AS n FROM orders WHERE status <> 'completed'"},
{s:'!=', d:'Not equal to. Identical to <> in PostgreSQL; <> is the portable one.', ex:"SELECT COUNT(*) AS n FROM orders WHERE status != 'cancelled'"},
{s:'<   >', d:'Less than / greater than.', ex:"SELECT COUNT(*) AS n FROM employees WHERE salary > 120000"},
{s:'<=  >=', d:'Less than or equal / greater than or equal.', ex:"SELECT COUNT(*) AS n FROM employees WHERE salary >= 150000"},
{s:'BETWEEN a AND b', d:'Range test, INCLUSIVE of both ends. Same as a <= x AND x <= b.',
 ex:"SELECT COUNT(*) AS n FROM employees WHERE salary BETWEEN 100000 AND 150000"},
{s:'NOT BETWEEN a AND b', d:'Outside the range, exclusive of both ends.',
 ex:"SELECT COUNT(*) AS n FROM employees WHERE salary NOT BETWEEN 100000 AND 150000"},
{s:'IN (list)', d:'Matches any value in a list or subquery.',
 ex:"SELECT COUNT(*) AS n FROM customers WHERE country IN ('India','UK')"},
{s:'NOT IN (list)', d:'Matches none of them. DANGER: returns zero rows if the list contains a NULL.',
 ex:"SELECT COUNT(*) AS n FROM customers WHERE country NOT IN ('India','UK')"},
{s:'IS NULL', d:'Tests for a missing value. The ONLY correct way — = NULL is never true.',
 ex:"SELECT COUNT(*) AS n FROM customers WHERE city IS NULL"},
{s:'IS NOT NULL', d:'Tests that a value is present.', ex:"SELECT COUNT(*) AS n FROM customers WHERE city IS NOT NULL"},
{s:'IS DISTINCT FROM', d:'Like <>, but NULL-safe: treats NULL as a comparable value.',
 ex:"SELECT (NULL IS DISTINCT FROM NULL) AS both_null, (1 IS DISTINCT FROM NULL) AS one_null"},
{s:'IS NOT DISTINCT FROM', d:'Like =, but NULL-safe. NULL equals NULL here.',
 ex:"SELECT (NULL IS NOT DISTINCT FROM NULL) AS equal_nulls"},
{s:'IS TRUE / IS FALSE', d:'Tests a boolean, treating NULL as not-true rather than unknown.',
 ex:"SELECT (NULL IS TRUE) AS null_is_true, (false IS FALSE) AS false_is_false"},
{s:'EXISTS (subquery)', d:'TRUE if the subquery returns at least one row. Stops at the first match.',
 ex:"SELECT COUNT(*) AS n FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.cust_id=c.cust_id)"},
{s:'NOT EXISTS (subquery)', d:'TRUE if the subquery returns nothing. The NULL-safe way to write an anti-join.',
 ex:"SELECT COUNT(*) AS n FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.cust_id=c.cust_id)"},
{s:'x > ANY (subquery)', d:'True if x beats AT LEAST ONE value — i.e. greater than the minimum. ANY = SOME.',
 ex:"SELECT COUNT(*) AS n FROM employees WHERE salary > ANY (SELECT salary FROM employees WHERE dept_id=3)"},
{s:'x > ALL (subquery)', d:'True if x beats EVERY value — i.e. greater than the maximum.',
 ex:"SELECT COUNT(*) AS n FROM employees WHERE salary > ALL (SELECT salary FROM employees WHERE dept_id=3)"},

{sec:'5 · Pattern matching', note:'Text search inside WHERE.'},
{s:"LIKE 'A%'", d:'Pattern match. % = any number of characters, _ = exactly one character.',
 ex:"SELECT COUNT(*) AS n FROM customers WHERE cust_name LIKE 'A%'"},
{s:"LIKE '%data%'", d:'Contains. A LEADING % prevents the use of a normal index.',
 ex:"SELECT COUNT(*) AS n FROM products WHERE product_name LIKE '%Data%'"},
{s:"LIKE '_a%'", d:'Underscore matches exactly one character — here, second letter is "a".',
 ex:"SELECT COUNT(*) AS n FROM customers WHERE cust_name LIKE '_a%'"},
{s:'NOT LIKE', d:'Does not match the pattern.', ex:"SELECT COUNT(*) AS n FROM customers WHERE cust_name NOT LIKE 'A%'"},
{s:'ILIKE', d:'PostgreSQL: case-insensitive LIKE.', ex:"SELECT COUNT(*) AS n FROM customers WHERE cust_name ILIKE '%o%'"},
{s:"ESCAPE '\\'", d:'Lets you search for a literal % or _ character.', ex:"SELECT '100%' LIKE '100\\%' AS matches_literal_percent"},
{s:'~   ~*', d:'PostgreSQL regex match / case-insensitive regex match.', ex:"SELECT 'abc123' ~ '[0-9]+$' AS ends_with_digits"},
{s:'!~  !~*', d:'Regex does NOT match / case-insensitively.', ex:"SELECT 'abc' !~ '[0-9]' AS has_no_digit"},
{s:'SIMILAR TO', d:'SQL-standard pattern language, halfway between LIKE and regex. Rarely worth it.',
 ex:"SELECT 'abc' SIMILAR TO '(a|z)%' AS matches"},

{sec:'6 · Logical operators', note:'Combining conditions. AND binds tighter than OR — bracket whenever you mix them.'},
{s:'AND', d:'Both sides must be true.', ex:"SELECT COUNT(*) AS n FROM orders WHERE status='completed' AND channel='web'"},
{s:'OR', d:'Either side may be true.', ex:"SELECT COUNT(*) AS n FROM orders WHERE status='cancelled' OR status='refunded'"},
{s:'NOT', d:'Inverts a condition. NOT UNKNOWN is still UNKNOWN.', ex:"SELECT COUNT(*) AS n FROM orders WHERE NOT (status='completed')"},
{s:'Precedence', d:'Highest to lowest: :: → unary − → * / % → + − → || → BETWEEN/IN/LIKE → comparisons → IS → NOT → AND → OR.',
 ex:null, plain:"a OR b AND c   ==   a OR (b AND c)"},
{s:'Three-valued logic', d:'TRUE AND NULL = NULL. FALSE AND NULL = FALSE. TRUE OR NULL = TRUE. FALSE OR NULL = NULL.',
 ex:"SELECT (true AND NULL) AS t_and_n, (false AND NULL) AS f_and_n, (true OR NULL) AS t_or_n, (false OR NULL) AS f_or_n"},

{sec:'7 · Arithmetic operators'},
{s:'+  −  *  /', d:'Add, subtract, multiply, divide.', ex:"SELECT 10+3 AS add, 10-3 AS sub, 10*3 AS mul, 10.0/3 AS div"},
{s:'/ on integers', d:'TRUNCATES — 7/2 is 3, not 3.5. Cast one side to numeric to get a decimal.',
 ex:"SELECT 7/2 AS integer_div, 7/2.0 AS decimal_div, 7::numeric/2 AS cast_div"},
{s:'%', d:'Modulo — the remainder after division.', ex:"SELECT 17 % 5 AS remainder"},
{s:'^', d:'Exponentiation.', ex:"SELECT 2 ^ 10 AS power"},
{s:'|/   ||/', d:'Square root / cube root operators.', ex:"SELECT |/ 144 AS sqrt, ||/ 27 AS cbrt"},
{s:'@', d:'Absolute value operator.', ex:"SELECT @ -17 AS absolute"},

{sec:'8 · Data types & casting', note:'What to store a value as, and how to convert between them.'},
{s:'integer / bigint / smallint', d:'Whole numbers. bigint for large IDs, integer for most things.', ex:"SELECT 42::integer AS i, 42::bigint AS b"},
{s:'numeric(p,s) / decimal', d:'EXACT decimal. The correct type for money — always.', ex:"SELECT 1234.5678::numeric(8,2) AS money"},
{s:'real / double precision', d:'Approximate floating point. Fast, but never use for money.',
 ex:"SELECT 0.1::float8+0.2::float8 AS float_sum, 0.1::numeric+0.2::numeric AS numeric_sum"},
{s:'text / varchar(n) / char(n)', d:'Strings. text is the PostgreSQL default; varchar(n) only when a length limit is a real rule.',
 ex:"SELECT 'abc'::text AS t, 'abc'::varchar(5) AS v"},
{s:'boolean', d:'TRUE / FALSE / NULL.', ex:"SELECT true AS t, false AS f, NULL::boolean AS unknown"},
{s:'date', d:'A calendar day, no time.', ex:"SELECT DATE '2024-05-15' AS d"},
{s:'timestamp', d:'Date and time with NO time zone.', ex:"SELECT TIMESTAMP '2024-05-15 14:30:00' AS ts"},
{s:'timestamptz', d:'Date and time, zone-aware. Use this for anything real-world.', ex:"SELECT TIMESTAMPTZ '2024-05-15 14:30:00+05:30' AS tstz"},
{s:'interval', d:'A duration. Add or subtract it from a date.', ex:"SELECT INTERVAL '1 month 3 days' AS span"},
{s:'uuid', d:'128-bit identifier, for distributed keys.', ex:"SELECT '11111111-2222-3333-4444-555555555555'::uuid AS id"},
{s:'jsonb', d:'Binary JSON — indexable and queryable, unlike plain json.', ex:`SELECT '{"a":1}'::jsonb -> 'a' AS value`},
{s:'array  type[]', d:'An ordered list in one column. PostgreSQL-specific.', ex:"SELECT ARRAY['a','b','c'] AS tags, (ARRAY['a','b','c'])[2] AS second"},
{s:'CAST(x AS type)', d:'Convert a value to another type. ANSI standard, works in every dialect.', ex:"SELECT CAST('42' AS integer) AS n"},
{s:'x::type', d:'PostgreSQL shorthand for CAST. Shorter, but not portable.', ex:"SELECT '2024-05-15'::date AS d, '42'::int AS n"},
{s:'GENERATED … AS IDENTITY', d:'Modern auto-incrementing key. Preferred over serial.', ex:null, plain:'id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY'},
{s:'serial / bigserial', d:'Legacy auto-increment. Still common in older schemas.', ex:null, plain:'id serial PRIMARY KEY'},

{sec:'9 · Conditional expressions', note:'if/else inside SQL, and the NULL toolkit.'},
{s:'CASE WHEN … THEN … ELSE … END', d:'Searched CASE: evaluates conditions in order, returns the first match. Omit ELSE and unmatched rows get NULL.',
 ex:"SELECT emp_name, CASE WHEN salary>=175000 THEN 'exec' WHEN salary>=130000 THEN 'senior' ELSE 'other' END AS band FROM employees LIMIT 4"},
{s:'CASE x WHEN v THEN … END', d:'Simple CASE: shorthand for equality against one expression only.',
 ex:"SELECT title, CASE title WHEN 'CEO' THEN 'founder' ELSE 'staff' END AS kind FROM employees LIMIT 3"},
{s:'COALESCE(a,b,c)', d:'Returns the first argument that is not NULL.', ex:"SELECT COALESCE(NULL, NULL, 'fallback') AS first_non_null"},
{s:'NULLIF(a,b)', d:'Returns NULL if a equals b, else a. The standard divide-by-zero guard.',
 ex:"SELECT 10/NULLIF(0,0) AS safe_divide, NULLIF(5,5) AS same, NULLIF(5,9) AS different"},
{s:'GREATEST(a,b,…)', d:'Largest of several values ACROSS COLUMNS (not down rows). Skips NULLs.', ex:"SELECT GREATEST(3,9,2) AS biggest"},
{s:'LEAST(a,b,…)', d:'Smallest of several values across columns. Skips NULLs.', ex:"SELECT LEAST(3,9,2) AS smallest"},

{sec:'10 · String functions', note:'Everything you might be asked to do to text.'},
{s:'a || b', d:'Concatenate. If EITHER side is NULL the whole result is NULL.', ex:"SELECT 'abc' || 'def' AS joined, 'abc' || NULL AS with_null"},
{s:'CONCAT(a,b,…)', d:'Concatenate, treating NULL as an empty string.', ex:"SELECT CONCAT('abc', NULL, 'def') AS joined"},
{s:'CONCAT_WS(sep,a,b,…)', d:'Concatenate with a separator, SKIPPING NULLs. Best for building addresses.',
 ex:"SELECT CONCAT_WS(', ', 'Mumbai', NULL, 'India') AS location"},
{s:'LENGTH(s) / CHAR_LENGTH(s)', d:'Number of characters.', ex:"SELECT LENGTH('hello') AS len"},
{s:'UPPER(s) / LOWER(s)', d:'Convert case.', ex:"SELECT UPPER('abc') AS up, LOWER('ABC') AS low"},
{s:'INITCAP(s)', d:'Capitalises the first letter of each word.', ex:"SELECT INITCAP('zenith retail ltd') AS titled"},
{s:'REPLACE(s, from, to)', d:'Replaces EVERY occurrence of one substring with another. Case-sensitive.',
 ex:"SELECT REPLACE('2024-01-05', '-', '/') AS swapped"},
{s:'TRANSLATE(s, from, to)', d:'Replaces individual CHARACTERS one-for-one, like a cipher.',
 ex:"SELECT TRANSLATE('2024-01-05', '-0', '/O') AS translated"},
{s:'SUBSTRING(s FROM p FOR n)', d:'n characters starting at position p (1-based). Also SUBSTRING(s, p, n).',
 ex:"SELECT SUBSTRING('abcdef' FROM 2 FOR 3) AS part, SUBSTRING('abcdef', 2, 3) AS same"},
{s:'LEFT(s,n) / RIGHT(s,n)', d:'First / last n characters.', ex:"SELECT LEFT('abcdef',3) AS l, RIGHT('abcdef',3) AS r"},
{s:'TRIM(s)', d:'Removes leading and trailing whitespace (or given characters).', ex:"SELECT '[' || TRIM('   abc   ') || ']' AS trimmed"},
{s:'LTRIM(s) / RTRIM(s)', d:'Trims only the left / only the right.', ex:"SELECT '[' || LTRIM('   abc') || ']' AS l, '[' || RTRIM('abc   ') || ']' AS r"},
{s:'BTRIM(s, chars)', d:'Trims the given characters from both ends.', ex:"SELECT BTRIM('xxabcxx','x') AS trimmed"},
{s:'LPAD(s,n,c) / RPAD(s,n,c)', d:'Pads to width n with character c. Used for fixed-width codes.',
 ex:"SELECT LPAD('7',3,'0') AS padded, RPAD('7',3,'-') AS right_padded"},
{s:'POSITION(sub IN s)', d:'1-based index of a substring; 0 if absent.', ex:"SELECT POSITION('cd' IN 'abcdef') AS idx"},
{s:'STRPOS(s, sub)', d:'Same as POSITION with the arguments the other way round.', ex:"SELECT STRPOS('abcdef','cd') AS idx"},
{s:'SPLIT_PART(s, delim, n)', d:'Returns the nth field after splitting. Ideal for emails, paths and codes.',
 ex:"SELECT SPLIT_PART('ops@zenith.example','@',2) AS domain"},
{s:'REPEAT(s,n)', d:'Repeats a string n times — used for indenting tree output.', ex:"SELECT REPEAT('ab',3) AS repeated"},
{s:'REVERSE(s)', d:'Reverses the characters.', ex:"SELECT REVERSE('abc') AS backwards"},
{s:'STARTS_WITH(s, prefix)', d:'Boolean prefix test; can use an index, unlike a regex.', ex:"SELECT STARTS_WITH('abcdef','abc') AS yes"},
{s:'FORMAT(fmt, args…)', d:'printf-style string building. %s = value, %I = identifier, %L = quoted literal.',
 ex:"SELECT FORMAT('Hi %s, you are %s', 'Asha', 30) AS greeting"},
{s:'REGEXP_REPLACE(s,pat,repl[,flags])', d:'Regex substitution. Add flag "g" to replace every match, not just the first.',
 ex:"SELECT REGEXP_REPLACE('a1b2c3','[0-9]','#','g') AS masked"},
{s:'REGEXP_MATCHES(s,pat)', d:'Returns captured groups as an array; with "g" returns one row per match.',
 ex:"SELECT (REGEXP_MATCHES('order-1234','([a-z]+)-([0-9]+)'))[2] AS number"},
{s:'REGEXP_SPLIT_TO_ARRAY(s,pat)', d:'Splits a string by a regex into an array.', ex:"SELECT REGEXP_SPLIT_TO_ARRAY('a1b22c','[0-9]+') AS parts"},
{s:'MD5(s)', d:'Hex MD5 hash — handy for building a change-detection fingerprint.', ex:"SELECT LEFT(MD5('abc'),12) AS hash_prefix"},
{s:'ASCII(c) / CHR(n)', d:'Character to code point and back.', ex:"SELECT ASCII('A') AS code, CHR(65) AS letter"},

{sec:'11 · Numeric functions'},
{s:'ROUND(x)', d:'Rounds to the nearest whole number.', ex:"SELECT ROUND(1234.5678) AS rounded"},
{s:'ROUND(x, n)', d:'Rounds to n decimal places. Needs numeric — ROUND(double, n) does not exist in PostgreSQL.',
 ex:"SELECT ROUND(1234.5678, 2) AS two_dp, ROUND(AVG(salary)::numeric, 2) AS avg_2dp FROM employees"},
{s:'CEIL(x) / CEILING(x)', d:'Rounds UP to the next whole number.', ex:"SELECT CEIL(4.1) AS up"},
{s:'FLOOR(x)', d:'Rounds DOWN.', ex:"SELECT FLOOR(4.9) AS down"},
{s:'TRUNC(x[,n])', d:'Chops off decimals without rounding.', ex:"SELECT TRUNC(4.99) AS chopped, TRUNC(4.99,1) AS one_dp"},
{s:'ABS(x)', d:'Absolute value.', ex:"SELECT ABS(-17) AS positive"},
{s:'MOD(a,b)', d:'Remainder of a divided by b.', ex:"SELECT MOD(17,5) AS remainder"},
{s:'DIV(a,b)', d:'Integer quotient, discarding the remainder.', ex:"SELECT DIV(17,5) AS quotient"},
{s:'POWER(a,b)', d:'a to the power of b.', ex:"SELECT POWER(2,10) AS result"},
{s:'SQRT(x) / CBRT(x)', d:'Square root / cube root.', ex:"SELECT SQRT(144) AS sq, CBRT(27) AS cb"},
{s:'EXP(x) / LN(x) / LOG(x)', d:'e^x, natural log, base-10 log.', ex:"SELECT ROUND(EXP(1)::numeric,4) AS e, LN(1) AS ln1, LOG(100) AS log100"},
{s:'SIGN(x)', d:'Returns −1, 0 or 1 depending on the sign.', ex:"SELECT SIGN(-5) AS neg, SIGN(0) AS zero, SIGN(5) AS pos"},
{s:'RANDOM()', d:'Random number in [0,1). Use with ORDER BY for a random sample.', ex:"SELECT (RANDOM() >= 0 AND RANDOM() < 1) AS always_true"},
{s:'WIDTH_BUCKET(x, lo, hi, n)', d:'Assigns a value to one of n equal-width buckets — histogram binning.',
 ex:"SELECT WIDTH_BUCKET(85000, 80000, 260000, 4) AS bucket"},

{sec:'12 · Date & time functions', note:'The single richest source of analyst interview questions.'},
{s:'CURRENT_DATE', d:'Today, as a date.', ex:"SELECT (CURRENT_DATE IS NOT NULL) AS works"},
{s:'NOW() / CURRENT_TIMESTAMP', d:'This instant, with time zone.', ex:"SELECT (NOW() IS NOT NULL) AS works"},
{s:'DATE_TRUNC(unit, ts)', d:'Rounds a date DOWN to the start of the unit. The workhorse for monthly grouping.',
 ex:"SELECT DATE_TRUNC('month', DATE '2024-05-15')::date AS month_start, DATE_TRUNC('week', DATE '2024-05-15')::date AS week_start"},
{s:'EXTRACT(field FROM ts)', d:'Pulls one field out as a number: YEAR, MONTH, DAY, QUARTER, DOW, DOY, HOUR, EPOCH.',
 ex:"SELECT EXTRACT(YEAR FROM DATE '2024-05-15') AS yr, EXTRACT(QUARTER FROM DATE '2024-05-15') AS qtr, EXTRACT(DOW FROM DATE '2024-05-15') AS dow"},
{s:'DATE_PART(field, ts)', d:'Function-call form of EXTRACT; identical result.', ex:"SELECT DATE_PART('month', DATE '2024-05-15') AS mth"},
{s:'TO_CHAR(ts, fmt)', d:'Formats a date as TEXT for display. YYYY MM DD Mon Day HH24 MI SS.',
 ex:"SELECT TO_CHAR(DATE '2024-05-15','YYYY-MM') AS label, TO_CHAR(DATE '2024-05-15','Mon DD, YYYY') AS pretty"},
{s:'TO_DATE(s, fmt)', d:'Parses text into a date using a format string.', ex:"SELECT TO_DATE('15/05/2024','DD/MM/YYYY') AS parsed"},
{s:'TO_TIMESTAMP(s, fmt)', d:'Parses text into a timestamp.', ex:"SELECT TO_TIMESTAMP('2024-05-15 14:30','YYYY-MM-DD HH24:MI') AS parsed"},
{s:'MAKE_DATE(y,m,d)', d:'Builds a date from three numbers.', ex:"SELECT MAKE_DATE(2024,5,15) AS built"},
{s:"d + INTERVAL '1 month'", d:'Date arithmetic. Units: year month week day hour minute second.',
 ex:"SELECT DATE '2024-01-31' + INTERVAL '1 month' AS next_month, DATE '2024-05-15' - INTERVAL '7 days' AS week_ago"},
{s:'date − date', d:'Difference between two dates, in whole DAYS (an integer).', ex:"SELECT DATE '2024-05-15' - DATE '2024-05-01' AS days_apart"},
{s:'AGE(a, b)', d:'Human-readable difference as an interval (years/months/days).', ex:"SELECT AGE(DATE '2024-05-15', DATE '2023-01-10') AS gap"},
{s:'EXTRACT(EPOCH FROM x)', d:'Converts an interval or timestamp to seconds — the way to get an exact numeric duration.',
 ex:"SELECT EXTRACT(EPOCH FROM (TIMESTAMP '2024-05-15 12:00' - TIMESTAMP '2024-05-15 10:30'))/3600 AS hours"},
{s:'OVERLAPS', d:'True if two date ranges overlap.',
 ex:"SELECT (DATE '2024-01-01', DATE '2024-06-30') OVERLAPS (DATE '2024-06-01', DATE '2024-12-31') AS ranges_overlap"},
{s:'generate_series(d1,d2,step)', d:'Builds a DATE SPINE so months with no data still appear as zero rows.',
 ex:"SELECT g::date AS month FROM generate_series(DATE '2024-01-01', DATE '2024-06-01', INTERVAL '1 month') g"},

{sec:'13 · Aggregate functions', note:'Many rows in, one value out. Every one of these ignores NULLs except COUNT(*).'},
{s:'COUNT(*)', d:'Counts ROWS, including rows that are entirely NULL.', ex:"SELECT COUNT(*) AS n FROM customers"},
{s:'COUNT(col)', d:'Counts NON-NULL values in that column. Almost always the source of a count mismatch.',
 ex:"SELECT COUNT(*) AS all_rows, COUNT(city) AS with_city FROM customers"},
{s:'COUNT(DISTINCT col)', d:'Counts distinct non-NULL values. The fix for fan-out double counting.',
 ex:"SELECT COUNT(DISTINCT country) AS countries FROM customers"},
{s:'SUM(col)', d:'Total. Skips NULLs; returns NULL (not 0) if every value is NULL.', ex:"SELECT SUM(salary) AS payroll FROM employees"},
{s:'AVG(col)', d:'Mean. Skips NULLs in BOTH the total and the divisor — so it may not be the average the business means.',
 ex:"SELECT ROUND(AVG(salary),0) AS mean_salary FROM employees"},
{s:'MIN(col) / MAX(col)', d:'Extremes. Work on numbers, text and dates alike.', ex:"SELECT MIN(salary) AS lowest, MAX(salary) AS highest FROM employees"},
{s:'STRING_AGG(col, sep)', d:'Glues values into one delimited string. Accepts its own ORDER BY.',
 ex:"SELECT STRING_AGG(dept_name, ', ' ORDER BY dept_name) AS all_depts FROM departments"},
{s:'ARRAY_AGG(col)', d:'Collects values into an array. Unlike STRING_AGG it keeps NULLs.',
 ex:"SELECT ARRAY_AGG(dept_id ORDER BY dept_id) AS ids FROM departments"},
{s:'BOOL_AND / BOOL_OR', d:'True if all / any values are true. EVERY() is a synonym for BOOL_AND.',
 ex:"SELECT BOOL_AND(salary>50000) AS all_above, BOOL_OR(salary>200000) AS any_above FROM employees"},
{s:'STDDEV / VARIANCE', d:'Sample standard deviation and variance. _POP variants give the population figures.',
 ex:"SELECT ROUND(STDDEV(salary),0) AS sd, ROUND(VARIANCE(salary),0) AS var FROM employees"},
{s:'PERCENTILE_CONT(f) WITHIN GROUP (ORDER BY x)', d:'MEDIAN at f=0.5 — interpolates between the two middle values.',
 ex:"SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY salary) AS median FROM employees"},
{s:'PERCENTILE_DISC(f) WITHIN GROUP (ORDER BY x)', d:'Percentile that returns an ACTUAL value from the data, never an interpolation.',
 ex:"SELECT PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY salary) AS median_actual FROM employees"},
{s:'MODE() WITHIN GROUP (ORDER BY x)', d:'The most frequently occurring value.', ex:"SELECT MODE() WITHIN GROUP (ORDER BY salary) AS most_common FROM employees"},
{s:'CORR(y,x)', d:'Pearson correlation coefficient between two columns.', ex:"SELECT ROUND(CORR(unit_price, cost)::numeric,4) AS correlation FROM products"},
{s:'agg(…) FILTER (WHERE cond)', d:'Aggregates only the rows matching a condition. The clean way to pivot. PostgreSQL/standard only.',
 ex:"SELECT COUNT(*) AS total, COUNT(*) FILTER (WHERE status='completed') AS completed FROM orders"},
{s:'SUM(CASE WHEN c THEN 1 ELSE 0 END)', d:'The portable equivalent of FILTER — works in MySQL and SQL Server too.',
 ex:"SELECT SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) AS completed FROM orders"},
{s:'agg(DISTINCT col)', d:'Aggregates only distinct values.', ex:"SELECT SUM(DISTINCT salary) AS distinct_payroll FROM employees"},

{sec:'14 · GROUP BY & HAVING', note:'Folding rows into groups, then filtering the groups.'},
{s:'GROUP BY col', d:'Folds rows into one row per distinct value. EVERY non-aggregated SELECT column must appear here.',
 ex:"SELECT country, COUNT(*) AS n FROM customers GROUP BY country ORDER BY n DESC"},
{s:'GROUP BY a, b', d:'One row per COMBINATION of values.',
 ex:"SELECT country, segment, COUNT(*) AS n FROM customers GROUP BY country, segment ORDER BY country, segment"},
{s:'GROUP BY 1', d:'Groups by the first SELECT column by position. Convenient; name it in production code.',
 ex:"SELECT DATE_TRUNC('month',order_date)::date AS m, COUNT(*) AS n FROM orders GROUP BY 1 ORDER BY 1"},
{s:'Aggregate with no GROUP BY', d:'Collapses the WHOLE table to a single row.', ex:"SELECT COUNT(*) AS n, ROUND(AVG(salary),0) AS avg FROM employees"},
{s:'THE RULE', d:'Every column in SELECT is either inside an aggregate, or listed in GROUP BY. There is no third option.',
 ex:null, plain:'SELECT dept_id, COUNT(*) … GROUP BY dept_id      ✓\nSELECT dept_id, emp_name, COUNT(*) … GROUP BY dept_id   ✗ error'},
{s:'HAVING cond', d:'Filters GROUPS after aggregation. The only place an aggregate may be used as a filter.',
 ex:"SELECT country, COUNT(*) AS n FROM customers GROUP BY country HAVING COUNT(*) > 1"},
{s:'WHERE vs HAVING', d:'WHERE filters rows before grouping; HAVING filters groups after. No aggregate in the condition → it belongs in WHERE.',
 ex:"SELECT cust_id, COUNT(*) AS n FROM orders WHERE status='completed' GROUP BY cust_id HAVING COUNT(*)>=3 ORDER BY n DESC"},
{s:'GROUP BY ROLLUP(a,b)', d:'Adds subtotal rows and a grand total — a hierarchy of totals in one pass.',
 ex:"SELECT country, COUNT(*) AS n, GROUPING(country) AS is_total FROM customers GROUP BY ROLLUP(country) ORDER BY is_total, country"},
{s:'GROUP BY CUBE(a,b)', d:'Every possible combination of subtotals.',
 ex:"SELECT country, segment, COUNT(*) AS n FROM customers GROUP BY CUBE(country, segment) ORDER BY country NULLS LAST, segment NULLS LAST"},
{s:'GROUP BY GROUPING SETS (…)', d:'You list exactly which grouping levels you want.',
 ex:"SELECT country, segment, COUNT(*) AS n FROM customers GROUP BY GROUPING SETS ((country),(segment),()) ORDER BY country NULLS LAST, segment NULLS LAST"},
{s:'GROUPING(col)', d:'Returns 1 when the row is a subtotal for that column — the only way to tell a subtotal NULL from a real NULL.',
 ex:"SELECT country, GROUPING(country) AS is_subtotal, COUNT(*) AS n FROM customers GROUP BY ROLLUP(country) ORDER BY is_subtotal DESC LIMIT 3"},

{sec:'15 · ORDER BY, LIMIT & OFFSET'},
{s:'ORDER BY col', d:'Sorts the final rows. Ascending by default. Without it there is NO guaranteed order.',
 ex:"SELECT emp_name, salary FROM employees ORDER BY salary DESC LIMIT 3"},
{s:'ASC / DESC', d:'Sort direction, per column.', ex:"SELECT cust_name, country FROM customers ORDER BY country ASC, cust_name DESC LIMIT 4"},
{s:'NULLS FIRST / NULLS LAST', d:'Where NULLs go. PostgreSQL default: last when ASC, first when DESC.',
 ex:"SELECT cust_name, city FROM customers ORDER BY city NULLS LAST LIMIT 4"},
{s:'ORDER BY alias', d:'Allowed, because ORDER BY runs AFTER SELECT.', ex:"SELECT emp_name, salary*12 AS annual FROM employees ORDER BY annual DESC LIMIT 3"},
{s:'ORDER BY 2', d:'Sorts by the second SELECT column, by position.', ex:"SELECT country, COUNT(*) AS n FROM customers GROUP BY country ORDER BY 2 DESC LIMIT 3"},
{s:'ORDER BY CASE …', d:'Custom, non-alphabetical ordering — e.g. a business status sequence.',
 ex:"SELECT status, COUNT(*) AS n FROM orders GROUP BY status ORDER BY CASE status WHEN 'pending' THEN 1 WHEN 'completed' THEN 2 WHEN 'refunded' THEN 3 ELSE 4 END"},
{s:'LIMIT n', d:'Return at most n rows.', ex:"SELECT emp_name FROM employees ORDER BY emp_id LIMIT 3"},
{s:'OFFSET m', d:'Skip the first m rows. Gets slower the deeper you page.', ex:"SELECT emp_name FROM employees ORDER BY emp_id LIMIT 3 OFFSET 3"},
{s:'FETCH FIRST n ROWS ONLY', d:'The ANSI spelling of LIMIT. PostgreSQL accepts both.', ex:"SELECT emp_name FROM employees ORDER BY emp_id FETCH FIRST 2 ROWS ONLY"},
{s:'Stable paging', d:'Always add a UNIQUE tie-break column to ORDER BY, or pages can repeat or skip rows.',
 ex:"SELECT emp_name, salary FROM employees ORDER BY salary DESC, emp_id LIMIT 3 OFFSET 2"},
{s:'Keyset pagination', d:'Replaces OFFSET with a row-value comparison. Constant speed at any depth.',
 ex:"SELECT emp_name, salary FROM employees WHERE (salary, emp_id) < (150000, 6) ORDER BY salary DESC, emp_id DESC LIMIT 3"},

{sec:'16 · JOINs', note:'Combining tables side by side. Mentally: every possible pairing, keeping the pairs where ON is true.'},
{s:'INNER JOIN … ON', d:'Keeps only rows that match on BOTH sides. The word INNER is optional.',
 ex:"SELECT COUNT(*) AS n FROM customers c INNER JOIN orders o ON o.cust_id=c.cust_id"},
{s:'LEFT JOIN … ON', d:'Keeps ALL left rows; right-side columns become NULL where there is no match.',
 ex:"SELECT COUNT(*) AS n FROM customers c LEFT JOIN orders o ON o.cust_id=c.cust_id"},
{s:'RIGHT JOIN … ON', d:'Keeps all RIGHT rows. Rare — flip the tables and write LEFT instead.',
 ex:"SELECT COUNT(*) AS n FROM orders o RIGHT JOIN customers c ON o.cust_id=c.cust_id"},
{s:'FULL OUTER JOIN … ON', d:'Keeps everything from both sides. Used to reconcile two systems.',
 ex:"SELECT COUNT(*) AS n FROM customers c FULL OUTER JOIN orders o ON o.cust_id=c.cust_id"},
{s:'CROSS JOIN', d:'Every combination — the Cartesian product. No ON clause. Used for date spines and grids.',
 ex:"SELECT COUNT(*) AS n FROM (SELECT 1 UNION SELECT 2) a CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3) b"},
{s:'USING (col)', d:'Shorthand for ON a.col = b.col when the column is named identically. Merges it into one output column.',
 ex:"SELECT COUNT(*) AS n FROM orders JOIN customers USING (cust_id)"},
{s:'NATURAL JOIN', d:'Joins on EVERY same-named column. Avoid it — adding a column later silently changes the query.',
 ex:null, plain:'FROM a NATURAL JOIN b     -- do not use'},
{s:'ON vs WHERE (outer join)', d:'On a LEFT JOIN, a condition on the right table in WHERE deletes the NULL rows and silently makes it an INNER join. Put it in ON.',
 ex:"SELECT (SELECT COUNT(*) FROM customers c LEFT JOIN orders o ON o.cust_id=c.cust_id AND o.status='completed') AS in_on, (SELECT COUNT(*) FROM customers c LEFT JOIN orders o ON o.cust_id=c.cust_id WHERE o.status='completed') AS in_where"},
{s:'Self join', d:'A table joined to itself with two aliases — for hierarchies and row-to-row comparisons.',
 ex:"SELECT e.emp_name AS employee, m.emp_name AS manager FROM employees e LEFT JOIN employees m ON m.emp_id=e.manager_id ORDER BY e.emp_id LIMIT 4"},
{s:'Anti-join', d:'Rows in A with NO match in B. Write it as NOT EXISTS, or LEFT JOIN … WHERE right IS NULL.',
 ex:"SELECT COUNT(*) AS never_ordered FROM products p WHERE NOT EXISTS (SELECT 1 FROM order_items i WHERE i.product_id=p.product_id)"},
{s:'Semi-join', d:'Rows in A that have AT LEAST ONE match in B, without duplicating A. Write it as EXISTS.',
 ex:"SELECT COUNT(*) AS ordered_at_least_once FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.cust_id=c.cust_id)"},
{s:'Non-equi join', d:'ON accepts any boolean, not just equality — used for banding and effective-dated records.',
 ex:"WITH b(label,lo,hi) AS (VALUES ('mid',100000,129999),('senior',130000,174999)) SELECT e.emp_name, b.label FROM employees e JOIN b ON e.salary BETWEEN b.lo AND b.hi ORDER BY e.salary LIMIT 4"},
{s:'Fan-out', d:'Joining a parent to a child MULTIPLIES the parent rows. Any SUM of a parent column is then double counted.',
 ex:"SELECT COUNT(*) AS rows_after_join, COUNT(DISTINCT o.order_id) AS actual_orders FROM orders o JOIN order_items oi ON oi.order_id=o.order_id"},
{s:'Aggregate-then-join', d:'When two child tables hang off one parent, aggregate each separately BEFORE joining, or the rows multiply together.',
 ex:"SELECT c.cust_name, COALESCE(i.rev,0) AS revenue FROM customers c LEFT JOIN (SELECT o.cust_id, SUM(oi.line_total) AS rev FROM orders o JOIN order_items oi ON oi.order_id=o.order_id GROUP BY o.cust_id) i ON i.cust_id=c.cust_id ORDER BY revenue DESC LIMIT 3"},

{sec:'17 · Set operations', note:'Stacking results on top of each other. Same column count, compatible types; names come from the first query.'},
{s:'UNION', d:'All rows from both queries, DUPLICATES REMOVED (which costs a sort or hash).',
 ex:"SELECT COUNT(*) AS n FROM (SELECT country FROM customers UNION SELECT country FROM customers) t"},
{s:'UNION ALL', d:'All rows from both, duplicates KEPT. Faster — make it your default.',
 ex:"SELECT COUNT(*) AS n FROM (SELECT country FROM customers UNION ALL SELECT country FROM customers) t"},
{s:'INTERSECT', d:'Only rows appearing in BOTH queries.',
 ex:"SELECT city FROM customers WHERE city IS NOT NULL INTERSECT SELECT location FROM departments"},
{s:'EXCEPT', d:'Rows in the first query that are NOT in the second. (MySQL/Oracle call it MINUS.)',
 ex:"SELECT city FROM customers WHERE city IS NOT NULL EXCEPT SELECT location FROM departments ORDER BY city"},
{s:'INTERSECT ALL / EXCEPT ALL', d:'Same, but keeping duplicate multiplicity.', ex:"SELECT 1 UNION ALL SELECT 1 INTERSECT ALL SELECT 1"},
{s:'NULL handling', d:'Set operations compare WHOLE ROWS and treat NULL as equal to NULL — unlike the = operator.',
 ex:"SELECT COUNT(*) AS n FROM (SELECT NULL::int UNION SELECT NULL::int) t"},
{s:'ORDER BY placement', d:'One ORDER BY, at the very end; it applies to the combined result.',
 ex:"SELECT cust_name AS name FROM customers WHERE country='UK' UNION ALL SELECT emp_name FROM employees WHERE dept_id=3 ORDER BY name"},

{sec:'18 · Subqueries', note:'A query inside a query. Where it sits determines what it must return.'},
{s:'Scalar subquery in SELECT', d:'Must return exactly ONE row and ONE column. Repeated on every output row.',
 ex:"SELECT emp_name, salary, (SELECT ROUND(AVG(salary)) FROM employees) AS company_avg FROM employees LIMIT 3"},
{s:'Scalar subquery in WHERE', d:'Compares each row against a single computed value.',
 ex:"SELECT COUNT(*) AS above_avg FROM employees WHERE salary > (SELECT AVG(salary) FROM employees)"},
{s:'Derived table in FROM', d:'A subquery used as a table. The alias is mandatory.',
 ex:"SELECT AVG(t.n) AS avg_per_dept FROM (SELECT dept_id, COUNT(*) AS n FROM employees GROUP BY dept_id) t"},
{s:'IN (subquery)', d:'Membership test against one column of any number of rows.',
 ex:"SELECT COUNT(*) AS n FROM orders WHERE cust_id IN (SELECT cust_id FROM customers WHERE country='India')"},
{s:'Correlated subquery', d:'References a column from the OUTER query, so conceptually it re-runs for every outer row.',
 ex:"SELECT COUNT(*) AS n FROM employees e WHERE e.salary > (SELECT AVG(e2.salary) FROM employees e2 WHERE e2.dept_id=e.dept_id)"},
{s:'Correlated scalar in SELECT', d:'Adds a per-row lookup — e.g. each customer with their own latest order date.',
 ex:"SELECT c.cust_name, (SELECT MAX(o.order_date) FROM orders o WHERE o.cust_id=c.cust_id) AS last_order FROM customers c ORDER BY c.cust_id LIMIT 4"},
{s:'LATERAL (subquery)', d:'Lets a FROM subquery see columns from the item before it. The clean top-N-per-group. SQL Server calls this CROSS APPLY.',
 ex:"SELECT d.dept_name, t.emp_name FROM departments d CROSS JOIN LATERAL (SELECT emp_name FROM employees e WHERE e.dept_id=d.dept_id ORDER BY salary DESC LIMIT 1) t"},
{s:'EXISTS vs IN vs JOIN', d:'EXISTS for "has any" (never duplicates rows). NOT EXISTS for "has none" (NULL-safe). JOIN when you need the other table columns.',
 ex:null, plain:'NOT IN + a NULL in the list  →  zero rows. Always prefer NOT EXISTS.'},

{sec:'19 · CTEs (WITH clause)', note:'Named intermediate results. The biggest readability upgrade available to you.'},
{s:'WITH name AS ( … )', d:'Defines a named temporary result used by the query below it.',
 ex:"WITH big AS (SELECT * FROM employees WHERE salary>130000) SELECT COUNT(*) AS n FROM big"},
{s:'Multiple CTEs', d:'Comma-separated; each may use any CTE defined above it.',
 ex:"WITH a AS (SELECT * FROM orders WHERE status='completed'), b AS (SELECT cust_id, COUNT(*) AS n FROM a GROUP BY cust_id) SELECT COUNT(*) AS customers FROM b"},
{s:'WITH RECURSIVE', d:'Anchor term, UNION ALL, then a recursive term that references the CTE. For hierarchies and series.',
 ex:"WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM n WHERE x<5) SELECT STRING_AGG(x::text,',') AS series FROM n"},
{s:'Recursive hierarchy', d:'Walk an org chart, tracking depth and path.',
 ex:"WITH RECURSIVE org AS (SELECT emp_id, emp_name, 1 AS lvl FROM employees WHERE manager_id IS NULL UNION ALL SELECT e.emp_id, e.emp_name, o.lvl+1 FROM employees e JOIN org o ON e.manager_id=o.emp_id) SELECT lvl, COUNT(*) AS people FROM org GROUP BY lvl ORDER BY lvl"},
{s:'Stop condition', d:'The recursive term MUST eventually return no rows, or the query never ends.',
 ex:null, plain:'… UNION ALL SELECT x+1 FROM n WHERE x < 100   -- the WHERE is the brake'},
{s:'MATERIALIZED / NOT MATERIALIZED', d:'Forces the planner to compute a CTE once, or to inline it. Default since PG12 is to inline when safe.',
 ex:"WITH x AS MATERIALIZED (SELECT 1 AS a) SELECT * FROM x"},
{s:'Data-modifying CTE', d:'INSERT/UPDATE/DELETE … RETURNING can be a CTE — how you move rows between tables atomically.',
 ex:null, plain:'WITH moved AS (DELETE FROM a WHERE … RETURNING *) INSERT INTO b SELECT * FROM moved;'},

{sec:'20 · Window functions', note:'Aggregate WITHOUT collapsing rows. The highest-value topic for an analyst interview.'},
{s:'fn() OVER ()', d:'Computes over ALL rows, adding a whole-table value to every row.',
 ex:"SELECT emp_name, salary, SUM(salary) OVER () AS total_payroll FROM employees LIMIT 3"},
{s:'OVER (PARTITION BY col)', d:'Splits rows into independent groups; the function restarts for each.',
 ex:"SELECT emp_name, dept_id, ROUND(AVG(salary) OVER (PARTITION BY dept_id)) AS dept_avg FROM employees WHERE dept_id IS NOT NULL ORDER BY dept_id LIMIT 4"},
{s:'OVER (ORDER BY col)', d:'Orders rows within the partition — and SILENTLY sets a running frame.',
 ex:"SELECT order_id, SUM(1) OVER (ORDER BY order_id) AS running_count FROM orders LIMIT 4"},
{s:'Default frame', d:'With ORDER BY the frame becomes RANGE UNBOUNDED PRECEDING TO CURRENT ROW, so aggregates become RUNNING totals. Without ORDER BY it is the whole partition.',
 ex:null, plain:'SUM(x) OVER (ORDER BY d)  =  running total, NOT a grand total'},
{s:'ROWS BETWEEN a AND b', d:'Frame counted in PHYSICAL ROWS. Usually what you actually mean.',
 ex:"SELECT order_id, ROUND(AVG(order_id) OVER (ORDER BY order_id ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),1) AS moving_avg FROM orders LIMIT 5"},
{s:'RANGE BETWEEN a AND b', d:'Frame counted in VALUES — all rows sharing the ORDER BY value (peers) are included together.',
 ex:"SELECT order_id, SUM(1) OVER (ORDER BY order_id RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS n FROM orders LIMIT 4"},
{s:'GROUPS BETWEEN a AND b', d:'Frame counted in peer GROUPS rather than rows or values.',
 ex:"SELECT order_id, SUM(1) OVER (ORDER BY order_id GROUPS BETWEEN 1 PRECEDING AND CURRENT ROW) AS n FROM orders LIMIT 4"},
{s:'UNBOUNDED PRECEDING / FOLLOWING', d:'The first / last row of the partition.',
 ex:"SELECT order_id, SUM(1) OVER (ORDER BY order_id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS all_rows FROM orders LIMIT 3"},
{s:'n PRECEDING / n FOLLOWING', d:'n rows back / forward from the current row.',
 ex:"SELECT order_id, SUM(1) OVER (ORDER BY order_id ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS window_size FROM orders LIMIT 4"},
{s:'EXCLUDE CURRENT ROW / TIES / GROUP', d:'Removes rows from the frame — e.g. an average of everyone EXCEPT me.',
 ex:"SELECT order_id, SUM(1) OVER (ORDER BY order_id ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING EXCLUDE CURRENT ROW) AS others FROM orders LIMIT 3"},
{s:'ROW_NUMBER()', d:'1,2,3… always distinct, arbitrary on ties. Use for de-duplication and exact top-N.',
 ex:"SELECT emp_name, salary, ROW_NUMBER() OVER (ORDER BY salary DESC) AS rn FROM employees LIMIT 5"},
{s:'RANK()', d:'Ties share a rank and leave a GAP: 1,1,3.',
 ex:"SELECT emp_name, salary, RANK() OVER (ORDER BY salary DESC) AS rnk FROM employees LIMIT 5"},
{s:'DENSE_RANK()', d:'Ties share a rank with NO gap: 1,1,2. Use for "top 3 distinct salaries".',
 ex:"SELECT emp_name, salary, DENSE_RANK() OVER (ORDER BY salary DESC) AS drnk FROM employees LIMIT 5"},
{s:'PERCENT_RANK()', d:'Relative rank from 0 to 1: (rank − 1) / (rows − 1).',
 ex:"SELECT emp_name, ROUND(PERCENT_RANK() OVER (ORDER BY salary)::numeric,3) AS pct FROM employees LIMIT 4"},
{s:'CUME_DIST()', d:'Cumulative distribution — the fraction of rows at or below this one.',
 ex:"SELECT emp_name, ROUND(CUME_DIST() OVER (ORDER BY salary)::numeric,3) AS cd FROM employees LIMIT 4"},
{s:'NTILE(n)', d:'Splits rows into n roughly equal buckets — quartiles, deciles.',
 ex:"SELECT emp_name, salary, NTILE(4) OVER (ORDER BY salary) AS quartile FROM employees LIMIT 5"},
{s:'LAG(col[,offset[,default]])', d:'Value from a PREVIOUS row. The basis of period-over-period change.',
 ex:"SELECT order_id, LAG(order_id) OVER (ORDER BY order_id) AS prev FROM orders LIMIT 4"},
{s:'LEAD(col[,offset[,default]])', d:'Value from a FOLLOWING row.',
 ex:"SELECT order_id, LEAD(order_id) OVER (ORDER BY order_id) AS next FROM orders LIMIT 4"},
{s:'FIRST_VALUE(col)', d:'First value in the frame. Correct with the default frame.',
 ex:"SELECT dept_id, emp_name, FIRST_VALUE(emp_name) OVER (PARTITION BY dept_id ORDER BY salary DESC) AS top_earner FROM employees WHERE dept_id IS NOT NULL ORDER BY dept_id LIMIT 4"},
{s:'LAST_VALUE(col)', d:'Last value in the frame — returns the CURRENT row unless you widen the frame explicitly.',
 ex:"SELECT dept_id, emp_name, LAST_VALUE(emp_name) OVER (PARTITION BY dept_id ORDER BY salary DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS lowest_paid FROM employees WHERE dept_id IS NOT NULL ORDER BY dept_id LIMIT 4"},
{s:'NTH_VALUE(col, n)', d:'The nth value in the frame.',
 ex:"SELECT dept_id, NTH_VALUE(emp_name,2) OVER (PARTITION BY dept_id ORDER BY salary DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS second FROM employees WHERE dept_id IS NOT NULL LIMIT 4"},
{s:'SUM/AVG/COUNT/MIN/MAX OVER', d:'Any aggregate can be a window function — running totals, moving averages, share of total.',
 ex:"SELECT emp_name, salary, ROUND(100.0*salary/SUM(salary) OVER (),2) AS pct_of_payroll FROM employees LIMIT 4"},
{s:'WINDOW w AS ( … )', d:'Names a window spec so several functions can reuse it. Sits between HAVING and ORDER BY.',
 ex:"SELECT emp_name, RANK() OVER w AS rnk, DENSE_RANK() OVER w AS drnk FROM employees WINDOW w AS (ORDER BY salary DESC) LIMIT 4"},
{s:'Not allowed in WHERE/GROUP BY/HAVING', d:'Windows are computed at step 6, after those clauses. Wrap the query in a CTE and filter outside.',
 ex:"WITH r AS (SELECT emp_name, dept_id, RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rk FROM employees WHERE dept_id IS NOT NULL) SELECT * FROM r WHERE rk<=2 ORDER BY dept_id, rk"},
{s:'Window over an aggregate', d:'Windows run AFTER GROUP BY, so you can rank grouped rows. SUM(SUM(x)) OVER () is the grand total of the groups.',
 ex:"SELECT country, COUNT(*) AS n, ROUND(100.0*COUNT(*)/SUM(COUNT(*)) OVER (),1) AS pct FROM customers GROUP BY country ORDER BY n DESC"},

{sec:'21 · DDL — defining tables', note:'Data Definition Language: the SHAPE of the data. Examples build demo_ tables so nothing else is disturbed.'},
{s:'CREATE TABLE t ( … )', d:'Creates a table. Commas BETWEEN column definitions, none after the last.',
 ex:"DROP TABLE IF EXISTS demo_t; CREATE TABLE demo_t (id integer, name text); SELECT 'created' AS status"},
{s:'IF NOT EXISTS', d:'Makes creation idempotent — no error if it is already there.',
 ex:"CREATE TABLE IF NOT EXISTS demo_t (id integer); SELECT 'ok' AS status"},
{s:'PRIMARY KEY', d:'The row identity. Implies UNIQUE + NOT NULL. One per table.',
 ex:"DROP TABLE IF EXISTS demo_pk; CREATE TABLE demo_pk (id integer PRIMARY KEY, v text); SELECT 'ok' AS status"},
{s:'PRIMARY KEY (a, b)', d:'Composite key across several columns — only expressible at table level.',
 ex:"DROP TABLE IF EXISTS demo_ck; CREATE TABLE demo_ck (a integer, b integer, PRIMARY KEY (a,b)); SELECT 'ok' AS status"},
{s:'UNIQUE', d:'No two rows share a value — but MANY NULLs are still allowed, because NULL <> NULL.',
 ex:"DROP TABLE IF EXISTS demo_u; CREATE TABLE demo_u (code text UNIQUE); INSERT INTO demo_u VALUES (NULL),(NULL),(NULL); SELECT COUNT(*) AS nulls_allowed FROM demo_u"},
{s:'NOT NULL', d:'A value must be supplied.',
 ex:"DROP TABLE IF EXISTS demo_nn; CREATE TABLE demo_nn (a integer NOT NULL); SELECT 'ok' AS status"},
{s:'DEFAULT value', d:'Value used when none is given on insert.',
 ex:"DROP TABLE IF EXISTS demo_d; CREATE TABLE demo_d (a integer, country text DEFAULT 'India'); INSERT INTO demo_d (a) VALUES (1); SELECT * FROM demo_d"},
{s:'CHECK (condition)', d:'An arbitrary per-row rule. Passes if it evaluates to NULL.',
 ex:"DROP TABLE IF EXISTS demo_c; CREATE TABLE demo_c (age integer CHECK (age >= 18)); SELECT 'ok' AS status"},
{s:'CONSTRAINT name CHECK (…)', d:'A NAMED constraint — so the error message and any later DROP can refer to it.',
 ex:"DROP TABLE IF EXISTS demo_nc; CREATE TABLE demo_nc (p numeric, c numeric, CONSTRAINT price_above_cost CHECK (p > c)); SELECT 'ok' AS status"},
{s:'REFERENCES t(col)', d:'Foreign key — the value must exist in the parent table.',
 ex:"DROP TABLE IF EXISTS demo_child; CREATE TABLE demo_child (id integer, pk_id integer REFERENCES demo_pk(id)); SELECT 'ok' AS status"},
{s:'ON DELETE CASCADE', d:'Deleting the parent deletes the children. For rows with no meaning alone, e.g. order_items.',
 ex:null, plain:'order_id integer REFERENCES orders(order_id) ON DELETE CASCADE'},
{s:'ON DELETE RESTRICT / NO ACTION', d:'Refuses to delete a parent that still has children. RESTRICT checks immediately.',
 ex:null, plain:'product_id integer REFERENCES products(product_id) ON DELETE RESTRICT'},
{s:'ON DELETE SET NULL / SET DEFAULT', d:'Blanks the child FK instead of deleting the child row.',
 ex:null, plain:'dept_id integer REFERENCES departments(dept_id) ON DELETE SET NULL'},
{s:'GENERATED ALWAYS AS (expr) STORED', d:'A column the DATABASE computes; you never write to it.',
 ex:"DROP TABLE IF EXISTS demo_g; CREATE TABLE demo_g (q integer, p numeric, total numeric GENERATED ALWAYS AS (q*p) STORED); INSERT INTO demo_g (q,p) VALUES (3,10); SELECT * FROM demo_g"},
{s:'ALTER TABLE … ADD COLUMN', d:'Adds a column.', ex:"ALTER TABLE demo_t ADD COLUMN city text; SELECT 'ok' AS status"},
{s:'ALTER TABLE … DROP COLUMN', d:'Removes a column and its data.', ex:"ALTER TABLE demo_t DROP COLUMN city; SELECT 'ok' AS status"},
{s:'ALTER TABLE … RENAME COLUMN', d:'Renames a column.', ex:"ALTER TABLE demo_t RENAME COLUMN name TO full_name; SELECT 'ok' AS status"},
{s:'ALTER TABLE … RENAME TO', d:'Renames the table.', ex:"ALTER TABLE demo_t RENAME TO demo_t2; ALTER TABLE demo_t2 RENAME TO demo_t; SELECT 'ok' AS status"},
{s:'ALTER TABLE … ALTER COLUMN TYPE', d:'Changes a column type; USING supplies the conversion when it is not automatic.',
 ex:"ALTER TABLE demo_t ALTER COLUMN id TYPE bigint; SELECT 'ok' AS status"},
{s:'ALTER TABLE … SET/DROP NOT NULL', d:'Adds or removes the NOT NULL rule.', ex:"ALTER TABLE demo_t ALTER COLUMN id SET NOT NULL; SELECT 'ok' AS status"},
{s:'ALTER TABLE … ADD/DROP CONSTRAINT', d:'Adds or removes a named constraint after the fact.',
 ex:"ALTER TABLE demo_t ADD CONSTRAINT id_positive CHECK (id > 0); ALTER TABLE demo_t DROP CONSTRAINT id_positive; SELECT 'ok' AS status"},
{s:'DROP TABLE [IF EXISTS] t [CASCADE]', d:'Removes the TABLE ITSELF. CASCADE also drops dependent objects.',
 ex:"DROP TABLE IF EXISTS demo_gone; SELECT 'ok' AS status"},
{s:'TRUNCATE TABLE t', d:'Removes ALL rows fast, keeping the table. No WHERE, no triggers. In PostgreSQL it IS transactional.',
 ex:"DROP TABLE IF EXISTS demo_tr; CREATE TABLE demo_tr (a int); INSERT INTO demo_tr VALUES (1),(2); TRUNCATE TABLE demo_tr; SELECT COUNT(*) AS rows_left FROM demo_tr"},
{s:'CREATE TABLE … AS SELECT', d:'"CTAS" — builds a new table from a query result.',
 ex:"DROP TABLE IF EXISTS demo_ctas; CREATE TABLE demo_ctas AS SELECT country, COUNT(*) AS n FROM customers GROUP BY country; SELECT COUNT(*) AS rows FROM demo_ctas"},
{s:'CREATE TEMP TABLE', d:'A table that disappears at the end of the session.',
 ex:"CREATE TEMP TABLE demo_tmp AS SELECT 1 AS a; SELECT * FROM demo_tmp"},
{s:'CREATE INDEX', d:'Speeds up reads on a column, at the cost of slower writes.',
 ex:"CREATE INDEX IF NOT EXISTS idx_demo ON demo_ctas (country); SELECT 'ok' AS status"},
{s:'CREATE UNIQUE INDEX', d:'Index that also enforces uniqueness.',
 ex:"DROP TABLE IF EXISTS demo_ui; CREATE TABLE demo_ui (a int); CREATE UNIQUE INDEX idx_ui ON demo_ui (a); SELECT 'ok' AS status"},
{s:'CREATE INDEX … (a, b)', d:'Composite index. Serves filters on a, or a AND b — but NOT b alone (leftmost-prefix rule).',
 ex:"CREATE INDEX IF NOT EXISTS idx_demo2 ON demo_ctas (country, n); SELECT 'ok' AS status"},
{s:'CREATE INDEX … WHERE cond', d:'PARTIAL index — indexes only the rows you actually query. Smaller and faster.',
 ex:"CREATE INDEX IF NOT EXISTS idx_demo3 ON demo_ctas (n) WHERE n > 1; SELECT 'ok' AS status"},
{s:'CREATE INDEX … (LOWER(col))', d:'EXPRESSION index — makes a function-wrapped WHERE sargable again.',
 ex:"CREATE INDEX IF NOT EXISTS idx_demo4 ON demo_ctas (LOWER(country)); SELECT 'ok' AS status"},
{s:'DROP INDEX', d:'Removes an index.', ex:"DROP INDEX IF EXISTS idx_demo4; SELECT 'ok' AS status"},

{sec:'22 · DML — changing data', note:'Data Manipulation Language: the ROWS, not the shape.'},
{s:'INSERT INTO t (cols) VALUES (…)', d:'Adds one row. ALWAYS name the columns — positional inserts break when a column is added.',
 ex:"DROP TABLE IF EXISTS demo_i; CREATE TABLE demo_i (id int, name text); INSERT INTO demo_i (id,name) VALUES (1,'Asha'); SELECT * FROM demo_i"},
{s:'INSERT … VALUES (…),(…),(…)', d:'Multi-row insert in ONE statement — far faster than many statements.',
 ex:"INSERT INTO demo_i (id,name) VALUES (2,'Ben'),(3,'Cara'); SELECT COUNT(*) AS rows FROM demo_i"},
{s:'INSERT … SELECT', d:'Inserts the result of a query.',
 ex:"INSERT INTO demo_i (id,name) SELECT 10+cust_id, cust_name FROM customers LIMIT 2; SELECT COUNT(*) AS rows FROM demo_i"},
{s:'RETURNING *', d:'PostgreSQL: gives back the rows actually written, including generated defaults.',
 ex:"INSERT INTO demo_i (id,name) VALUES (99,'Zed') RETURNING id, name"},
{s:'UPDATE t SET c = v WHERE …', d:'Changes existing rows. Commas BETWEEN assignments. Omit WHERE and you update EVERY row.',
 ex:"UPDATE demo_i SET name='Updated' WHERE id=1 RETURNING id, name"},
{s:'UPDATE … FROM other', d:'PostgreSQL: update using values joined from another table.',
 ex:"UPDATE demo_i d SET name=c.cust_name FROM customers c WHERE c.cust_id=d.id RETURNING d.id, d.name"},
{s:'DELETE FROM t WHERE …', d:'Removes rows. Omit WHERE and the table is emptied.',
 ex:"DELETE FROM demo_i WHERE id=99 RETURNING id"},
{s:'DELETE … USING other', d:'PostgreSQL: delete based on a join to another table.',
 ex:"DELETE FROM demo_i USING customers c WHERE c.cust_id=demo_i.id AND c.country='Nowhere'; SELECT COUNT(*) AS remaining FROM demo_i"},
{s:'INSERT … ON CONFLICT DO NOTHING', d:'UPSERT: skip the row silently if it already exists.',
 ex:"DROP TABLE IF EXISTS demo_up; CREATE TABLE demo_up (sku text PRIMARY KEY, qty int); INSERT INTO demo_up VALUES ('A1',10); INSERT INTO demo_up VALUES ('A1',99) ON CONFLICT (sku) DO NOTHING; SELECT * FROM demo_up"},
{s:'INSERT … ON CONFLICT DO UPDATE', d:'UPSERT: update the existing row instead. EXCLUDED is the row you TRIED to insert.',
 ex:"INSERT INTO demo_up (sku,qty) VALUES ('A1',4),('C3',7) ON CONFLICT (sku) DO UPDATE SET qty = demo_up.qty + EXCLUDED.qty RETURNING sku, qty"},
{s:'MERGE INTO … USING … WHEN', d:'ANSI upsert (PG15+). The standard answer in SQL Server and Oracle.',
 ex:"MERGE INTO demo_up t USING (VALUES ('B2',100)) AS s(sku,qty) ON t.sku=s.sku WHEN MATCHED THEN UPDATE SET qty=s.qty WHEN NOT MATCHED THEN INSERT (sku,qty) VALUES (s.sku,s.qty); SELECT COUNT(*) AS rows FROM demo_up"},

{sec:'23 · Transactions & concurrency'},
{s:'BEGIN … COMMIT', d:'Groups statements so they all succeed or all fail. ACID: Atomicity, Consistency, Isolation, Durability.',
 ex:"BEGIN; INSERT INTO demo_up VALUES ('T1',1); COMMIT; SELECT COUNT(*) AS rows FROM demo_up"},
{s:'ROLLBACK', d:'Undoes everything since BEGIN.',
 ex:"BEGIN; DELETE FROM demo_up; ROLLBACK; SELECT COUNT(*) AS still_there FROM demo_up"},
{s:'SAVEPOINT / ROLLBACK TO', d:'A partial undo point inside a transaction.',
 ex:"BEGIN; SAVEPOINT sp1; DELETE FROM demo_up; ROLLBACK TO sp1; COMMIT; SELECT COUNT(*) AS rows FROM demo_up"},
{s:'READ COMMITTED', d:'PostgreSQL DEFAULT. No dirty reads; non-repeatable reads and phantoms still possible.', ex:null, plain:'BEGIN ISOLATION LEVEL READ COMMITTED;'},
{s:'REPEATABLE READ', d:'MySQL default. Rows you re-read do not change. In PostgreSQL this also blocks phantoms.', ex:null, plain:'BEGIN ISOLATION LEVEL REPEATABLE READ;'},
{s:'SERIALIZABLE', d:'Strictest: the result is as if transactions ran one after another.', ex:null, plain:'BEGIN ISOLATION LEVEL SERIALIZABLE;'},
{s:'Dirty read', d:'Reading another transaction UNCOMMITTED change. Impossible in PostgreSQL at any level.', ex:null, plain:'prevented by READ COMMITTED and above'},
{s:'Non-repeatable read', d:'Reading the same ROW twice and getting different values.', ex:null, plain:'prevented by REPEATABLE READ and above'},
{s:'Phantom read', d:'Re-running a RANGE query and finding new rows.', ex:null, plain:'prevented by SERIALIZABLE (and by PG REPEATABLE READ)'},
{s:'Lost update', d:'Two transactions read-modify-write; one silently overwrites the other. Prevent with SELECT … FOR UPDATE.', ex:null, plain:'SELECT … FOR UPDATE;'},
{s:'SELECT … FOR UPDATE', d:'Locks the selected rows so nobody else can change them until you commit.', ex:null, plain:'SELECT * FROM accounts WHERE id=1 FOR UPDATE;'},
{s:'FOR UPDATE SKIP LOCKED', d:'Takes only rows nobody else holds — the queue-worker pattern.', ex:null, plain:"SELECT * FROM jobs WHERE state='new' LIMIT 1 FOR UPDATE SKIP LOCKED;"},
{s:'MVCC', d:'PostgreSQL keeps multiple row versions, so READERS NEVER BLOCK WRITERS and writers never block readers.', ex:null, plain:'the one-line answer to "how does Postgres handle concurrency?"'},
{s:'Deadlock', d:'Two transactions each hold what the other needs. PostgreSQL detects it and kills one. Prevent by always locking in the same order.', ex:null, plain:'keep transactions short; lock in a consistent order'},

{sec:'24 · Views, functions & triggers'},
{s:'CREATE VIEW v AS SELECT …', d:'A SAVED QUERY. Stores no data, always current, as slow as the underlying query.',
 ex:"CREATE OR REPLACE VIEW demo_v AS SELECT country, COUNT(*) AS n FROM customers GROUP BY country; SELECT * FROM demo_v ORDER BY n DESC LIMIT 3"},
{s:'CREATE MATERIALIZED VIEW', d:'STORES the result. Fast to read, can be indexed, but goes stale until refreshed.',
 ex:"DROP MATERIALIZED VIEW IF EXISTS demo_mv; CREATE MATERIALIZED VIEW demo_mv AS SELECT country, COUNT(*) AS n FROM customers GROUP BY country; SELECT COUNT(*) AS rows FROM demo_mv"},
{s:'REFRESH MATERIALIZED VIEW', d:'Recomputes it. CONCURRENTLY avoids locking readers (needs a unique index).',
 ex:"REFRESH MATERIALIZED VIEW demo_mv; SELECT 'refreshed' AS status"},
{s:'CREATE FUNCTION … RETURNS', d:'Returns a value or a table, and CAN be used inside a query.',
 ex:"CREATE OR REPLACE FUNCTION demo_double(x integer) RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT x*2 $$; SELECT demo_double(21) AS result"},
{s:'CREATE PROCEDURE … / CALL', d:'Returns nothing and CANNOT be used inside a query — but it CAN commit internally. That is the reason to use one.',
 ex:null, plain:'CREATE PROCEDURE p() LANGUAGE plpgsql AS $$ BEGIN … COMMIT; END $$;   CALL p();'},
{s:'CREATE TRIGGER', d:'Runs a function automatically on INSERT/UPDATE/DELETE. OLD and NEW are the row before and after.',
 ex:null, plain:'CREATE TRIGGER trg AFTER UPDATE ON t FOR EACH ROW EXECUTE FUNCTION f();'},
{s:'BEFORE vs AFTER trigger', d:'BEFORE can modify NEW or cancel the write; AFTER cannot, and is used for auditing.', ex:null, plain:'BEFORE → validate/modify   |   AFTER → log/cascade'},

{sec:'25 · Performance & inspection'},
{s:'EXPLAIN query', d:'Shows the PLAN and estimated cost without running the query.', ex:"EXPLAIN SELECT * FROM orders WHERE status='completed'"},
{s:'EXPLAIN ANALYZE query', d:'Actually RUNS it and reports real times and real row counts. Always start here.',
 ex:"EXPLAIN ANALYZE SELECT COUNT(*) FROM orders WHERE status='completed'"},
{s:'Seq Scan', d:'Reads the whole table. Fine on small tables; a red flag on a big one with a selective filter.', ex:null, plain:'fix: add an index on the filtered column'},
{s:'Index Scan / Index Only Scan', d:'Walks the index. "Index Only" means the answer came from the index alone — the best case.', ex:null, plain:'Index Only Scan is why you avoid SELECT *'},
{s:'Nested Loop / Hash Join / Merge Join', d:'The three join strategies: probe per row / build a hash table / zip two sorted inputs.', ex:null, plain:'Nested Loop is bad when the outer side is large'},
{s:'Estimated vs actual rows', d:'A big gap means the planner statistics are stale. Run ANALYZE on the table.', ex:null, plain:'rows=1000 … actual rows=2000000  →  ANALYZE tablename;'},
{s:'Sargable', d:'A predicate an index can serve. Keep the COLUMN bare on one side; do the arithmetic on the other.',
 ex:null, plain:"EXTRACT(YEAR FROM d)=2024   ✗\nd >= '2024-01-01' AND d < '2025-01-01'   ✓"},
{s:'Leftmost-prefix rule', d:'Index (a,b) serves filters on a, or a AND b — never b alone.', ex:null, plain:'equality columns first, range column last'},
{s:'information_schema.columns', d:'Standard catalogue view: inspect the columns of any table.',
 ex:"SELECT column_name, data_type FROM information_schema.columns WHERE table_name='customers' ORDER BY ordinal_position LIMIT 5"},
{s:'information_schema.tables', d:'Lists the tables in the database.',
 ex:"SELECT COUNT(*) AS tables FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE'"},

{sec:'26 · How NULL behaves, everywhere', note:'One table to settle every NULL argument. NULL means UNKNOWN, not zero and not blank.'},
{s:'= NULL', d:'NEVER true, not even NULL = NULL. Always use IS NULL.', ex:"SELECT (NULL = NULL) AS never_true, (NULL IS NULL) AS correct_test"},
{s:'NULL in arithmetic', d:'Any arithmetic involving NULL gives NULL.', ex:"SELECT NULL + 10 AS sum, NULL * 0 AS product"},
{s:'NULL in concatenation', d:"With || one NULL wipes the whole string. CONCAT and CONCAT_WS do not.",
 ex:"SELECT ('abc' || NULL) AS pipes, CONCAT('abc',NULL) AS concat_fn"},
{s:'NULL in COUNT', d:'COUNT(*) counts the row; COUNT(col) skips it.', ex:"SELECT COUNT(*) AS star, COUNT(city) AS col FROM customers"},
{s:'NULL in SUM / AVG', d:'Skipped. SUM of an all-NULL group is NULL, not 0. AVG divides by the NON-NULL count.',
 ex:"SELECT SUM(x) AS sum_all_null, AVG(x) AS avg_all_null FROM (SELECT NULL::int AS x) t"},
{s:'NULL in GROUP BY', d:'All NULLs collapse into ONE group.', ex:"SELECT COUNT(*) AS null_city_group FROM customers WHERE city IS NULL"},
{s:'NULL in ORDER BY', d:'PostgreSQL sorts NULLs LAST ascending, FIRST descending. Override with NULLS FIRST/LAST.',
 ex:"SELECT city FROM customers ORDER BY city DESC LIMIT 3"},
{s:'NULL in DISTINCT', d:'All NULLs count as ONE value.', ex:"SELECT COUNT(*) AS n FROM (SELECT DISTINCT city FROM customers) t"},
{s:'NULL in a JOIN key', d:'NULL never matches anything, not even another NULL — those rows simply drop out of an inner join.',
 ex:"SELECT COUNT(*) AS employees_kept FROM employees e JOIN departments d ON d.dept_id=e.dept_id"},
{s:'NULL in UNIQUE', d:'A UNIQUE constraint permits MANY NULL rows.', ex:"SELECT COUNT(*) AS n FROM demo_u"},
{s:'NULL in CHECK', d:'A CHECK constraint PASSES when its condition evaluates to NULL.', ex:null, plain:'CHECK (age >= 18) accepts a NULL age'},
{s:'NOT IN with a NULL', d:'Returns ZERO ROWS. The single most famous SQL trap. Use NOT EXISTS instead.',
 ex:"SELECT COUNT(*) AS with_not_in FROM departments WHERE dept_id NOT IN (SELECT dept_id FROM employees)"},

{sec:'27 · Interview patterns', note:'Twelve shapes that cover most of what gets asked. Learn the shape, not the query.'},
{s:'Nth highest value', d:'DENSE_RANK = N. Ask first whether ties share a rank, and whether N is by person or by distinct value.',
 ex:"WITH r AS (SELECT DISTINCT salary, DENSE_RANK() OVER (ORDER BY salary DESC) AS rk FROM employees) SELECT salary FROM r WHERE rk=3"},
{s:'Top N per group', d:'Rank inside a CTE partitioned by the group, then filter rn <= N outside.',
 ex:"WITH r AS (SELECT dept_id, emp_name, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rn FROM employees WHERE dept_id IS NOT NULL) SELECT dept_id, emp_name FROM r WHERE rn<=2 ORDER BY dept_id"},
{s:'Find duplicates', d:'GROUP BY the business key, HAVING COUNT(*) > 1.',
 ex:"SELECT LOWER(raw_email) AS email, COUNT(*) AS copies FROM staging_signups GROUP BY 1 HAVING COUNT(*)>1 ORDER BY copies DESC"},
{s:'De-duplicate, keep latest', d:'ROW_NUMBER partitioned by the key, ordered by recency; keep rn = 1. RANK would leave ties behind.',
 ex:"WITH r AS (SELECT raw_email, loaded_at, ROW_NUMBER() OVER (PARTITION BY LOWER(raw_email) ORDER BY loaded_at DESC) AS rn FROM staging_signups) SELECT COUNT(*) AS unique_rows FROM r WHERE rn=1"},
{s:'Running total', d:'SUM(x) OVER (ORDER BY d) — cumulative by default.',
 ex:"WITH m AS (SELECT DATE_TRUNC('month',order_date)::date AS mth, COUNT(*) AS n FROM orders GROUP BY 1) SELECT mth, n, SUM(n) OVER (ORDER BY mth) AS cumulative FROM m ORDER BY mth"},
{s:'Moving average', d:'AVG(x) OVER (ORDER BY d ROWS BETWEEN 2 PRECEDING AND CURRENT ROW).',
 ex:"WITH m AS (SELECT DATE_TRUNC('month',order_date)::date AS mth, COUNT(*) AS n FROM orders GROUP BY 1) SELECT mth, n, ROUND(AVG(n) OVER (ORDER BY mth ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS ma3 FROM m ORDER BY mth"},
{s:'Month-over-month growth', d:'LAG for the previous period, NULLIF to guard the division.',
 ex:"WITH m AS (SELECT DATE_TRUNC('month',order_date)::date AS mth, COUNT(*) AS n FROM orders GROUP BY 1) SELECT mth, n, ROUND(100.0*(n-LAG(n) OVER (ORDER BY mth))/NULLIF(LAG(n) OVER (ORDER BY mth),0),1) AS pct FROM m ORDER BY mth"},
{s:'Pivot rows into columns', d:'Conditional aggregation. PostgreSQL has no PIVOT keyword — FILTER or CASE is the pivot.',
 ex:"SELECT country, COUNT(*) FILTER (WHERE status='completed') AS completed, COUNT(*) FILTER (WHERE status='cancelled') AS cancelled FROM orders o JOIN customers c USING (cust_id) GROUP BY country ORDER BY country"},
{s:'Gaps and islands', d:'date − ROW_NUMBER() is CONSTANT inside a consecutive run. Group by that constant.',
 ex:"WITH d AS (SELECT DISTINCT event_at::date dt FROM web_events WHERE cust_id=1 AND event_type='page_view'), g AS (SELECT dt, dt-(ROW_NUMBER() OVER (ORDER BY dt))::int AS island FROM d) SELECT MIN(dt) AS run_start, MAX(dt) AS run_end, COUNT(*) AS days FROM g GROUP BY island ORDER BY run_start"},
{s:'Funnel conversion', d:'COUNT(DISTINCT id) FILTER per stage, then divide with NULLIF guards.',
 ex:"SELECT COUNT(DISTINCT session_id) FILTER (WHERE event_type='page_view') AS viewed, COUNT(DISTINCT session_id) FILTER (WHERE event_type='purchase') AS purchased FROM web_events"},
{s:'Fill date gaps', d:'Build a spine with generate_series and LEFT JOIN the aggregate ONTO the spine, not the other way round.',
 ex:"WITH s AS (SELECT g::date AS mth FROM generate_series(DATE '2024-01-01',DATE '2024-06-01',INTERVAL '1 month') g), a AS (SELECT DATE_TRUNC('month',order_date)::date AS mth, COUNT(*) AS n FROM orders WHERE channel='partner' GROUP BY 1) SELECT s.mth, COALESCE(a.n,0) AS partner_orders FROM s LEFT JOIN a ON a.mth=s.mth ORDER BY s.mth"},
{s:'Employees earning above their manager', d:'Self-join on manager_id, then compare the two salaries.',
 ex:"SELECT e.emp_name AS employee, e.salary, m.emp_name AS manager, m.salary AS mgr_salary FROM employees e JOIN employees m ON m.emp_id=e.manager_id WHERE e.salary>m.salary"},

{sec:'28 · Dialect differences', note:'If the interviewer switches engines mid-question, this is the table you want in your head.'},
{dialect:[
 ['Task','PostgreSQL','MySQL','SQL Server'],
 ['Limit rows','LIMIT 10 OFFSET 5','LIMIT 5, 10','OFFSET 5 ROWS FETCH NEXT 10 ROWS ONLY'],
 ['Top N','LIMIT 10','LIMIT 10','SELECT TOP 10'],
 ['Concatenate','a || b','CONCAT(a,b)','a + b'],
 ['NULL fallback','COALESCE(a,b)','IFNULL(a,b)','ISNULL(a,b)'],
 ['Current time','NOW()','NOW()','GETDATE()'],
 ['Month bucket',"DATE_TRUNC('month',d)","DATE_FORMAT(d,'%Y-%m-01')",'DATEFROMPARTS(YEAR(d),MONTH(d),1)'],
 ['Extract year','EXTRACT(YEAR FROM d)','YEAR(d)','YEAR(d)'],
 ['Date add',"d + INTERVAL '1 day'",'DATE_ADD(d,INTERVAL 1 DAY)','DATEADD(day,1,d)'],
 ['Date diff (days)','a - b','DATEDIFF(a,b)','DATEDIFF(day,b,a)'],
 ['Cast','x::int  /  CAST','CAST(x AS SIGNED)','CAST / CONVERT'],
 ['Case-insensitive LIKE','ILIKE','LIKE (collation)','LIKE (collation)'],
 ['String aggregate',"STRING_AGG(x,',')",'GROUP_CONCAT(x)',"STRING_AGG(x,',')"],
 ['Upsert','ON CONFLICT DO UPDATE','ON DUPLICATE KEY UPDATE','MERGE'],
 ['Auto id','GENERATED AS IDENTITY','AUTO_INCREMENT','IDENTITY(1,1)'],
 ['Quote identifier','"col"','`col`','[col]'],
 ['FULL OUTER JOIN','yes','no — emulate with UNION','yes'],
 ['Window functions','yes','yes (8.0+)','yes (2012+)'],
 ['FILTER (WHERE …)','yes','no — use CASE','no — use CASE'],
 ['Boolean type','yes','TINYINT(1)','BIT'],
 ['TRUNCATE rollback','yes','no','yes'],
 ['Default isolation','READ COMMITTED','REPEATABLE READ','READ COMMITTED'],
 ['Regex match','~  /  ~*','REGEXP','LIKE / PATINDEX'],
 ['LATERAL','LATERAL','LATERAL (8.0.14+)','CROSS APPLY'],
 ['GROUPING SETS','yes','WITH ROLLUP only','yes'],
]},
];
