/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesDashboardRouteImport } from './routes/sales-dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SalesDashboardRoute = SalesDashboardRouteImport.update({
  id: '/sales-dashboard',
  path: '/sales-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sales-dashboard': typeof SalesDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sales-dashboard': typeof SalesDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sales-dashboard': typeof SalesDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sales-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sales-dashboard'
  id: '__root__' | '/' | '/sales-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SalesDashboardRoute: typeof SalesDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales-dashboard': {
      id: '/sales-dashboard'
      path: '/sales-dashboard'
      fullPath: '/sales-dashboard'
      preLoaderRoute: typeof SalesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SalesDashboardRoute: SalesDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
